Fourth deliverable
StephanyPeralta/react-certification-2021 pull request #5
Opened 2021-08-26 04:05 UTC by StephanyPeralta

<img width="915" alt="Coverage_CH5" src="https://user-images.githubusercontent.com/73197053/130898825-cedec97f-2f0f-4ea5-834b-d7955b7ab0d9.png">

2021-08-27 22:58 UTC, omarscd requested changes
Esta vez no hay tantos comentarios sobre el código, pero sí de ciertas funcionalidades de la app que me gustaría ver:
- Presionar esc o hacer clic afuera del modal deberían cerrarlo.
- Al abrir el modal de login/logout el primer input debería obtener el foco para poder comenzar a escribir sin hacer clics adicionales.
- Agregar un mensaje o señal de que se inició sesión correctamente (un toast, por ejemplo).
- Separar los favoritos de cada usuario (lo que platicamos la otra vez)
- Estaría cool poder agregar o quitar de los favoritos sin tener que entrar a la página del video (este no es tan obligatorio)
- Dropdown de login/logout debería cerrarse al hacer clic en otro lado de la página

2021-08-27 22:58 UTC, omarscd commented on src/components/LoginForm/LoginForm.component.jsx
> +  const passwordRef = useRef();
por qué preferiste este patrón y no la típica combinación `useState` y `onChange={(e) => setState(e.target.value)}`?

2021-08-27 22:58 UTC, omarscd commented on src/components/ProfileButton/ProfileButton.component.jsx
> +      console.error(error);
creo que sería mejor notificar al usuario que la operación falló, puedes usar un Toast o algo similar para estas cositas

2021-08-27 22:58 UTC, omarscd commented on src/components/Header/Header.component.jsx
> +          YouWize
mejor ponle StephTube 👀 
(ntc, puedes ignorar este comentario)

2021-08-27 22:58 UTC, omarscd commented on src/providers/Selector/Selector.provider.jsx
> +    : [],
aquí estás llamando dos veces el método `get` para cada property, en este caso podrías hacer uso de un [Logcial OR (||)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR#examples) o un [Nullish coalescing operator (??)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)

2021-08-28 02:25 UTC, StephanyPeralta commented on src/components/LoginForm/LoginForm.component.jsx
> +  const passwordRef = useRef();
Ví que lo usaban en un tutorial y decidí probarlo además de que era uno de los temas del bootcamp.

2021-08-28 02:26 UTC, StephanyPeralta commented on src/components/ProfileButton/ProfileButton.component.jsx
> +      console.error(error);
Había puesto que apareciera un mensaje debajo del avatar, pero no me convenció por eso dejé el console.error 🙈 ... va checaré eso de los Toast para implementarlo, gracias 👍🏼 .

2021-08-28 02:26 UTC, StephanyPeralta commented on src/components/Header/Header.component.jsx
> +          YouWize
Andaba indecisa entre Steph o Wize pero por obvias razones ganó Wizeline😜.

2021-08-28 02:27 UTC, StephanyPeralta commented on src/providers/Selector/Selector.provider.jsx
> +    : [],
Va, trataré de implementarlo... gracias por el tip :).

2021-08-29 21:03 UTC, merged